#!/bin/bash
set -euo pipefail

if [ $# -lt 2 ] ; then
  echo "Usage: $(basename $0) patch|minor|major \"release message\""
  exit 1
fi

pushd ~/github.com/eyereasoner/eyeling > /dev/null

git commit -a -m "$2"
npm version "$1"
git push origin main --follow-tags

popd > /dev/null

