#!/bin/bash

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
NORMAL="\e[0;39m"

OK=0
DIFF=0

echo -e "${YELLOW}-------------------------------------------------${NORMAL}"
echo -e "${YELLOW}running eyeling examples${NORMAL}"
echo -e "${YELLOW}using node $(node --version)${NORMAL}"
echo -e "${YELLOW}-------------------------------------------------${NORMAL}"
echo ""

pad () {
    [ "$#" -gt 1 ]
    [ -n "$2" ]
    printf "%$2.${2#-}s" "$1"
}

begin=$(($(date +%s%N)/1000000))

for file in *.n3
do
    echo -en "$(pad "${file}" -36)"
    start=$(($(date +%s%N)/1000000))
    ../eyeling.js "${file}" > output/${file}
    end=$(($(date +%s%N)/1000000))
    echo -en "${YELLOW}$(pad "`expr $end - $start` ms" 10)${NORMAL} "
    if [[ $(git diff output/${file} | wc -l) -eq 0 ]]; then
        echo -e "${GREEN}OK${NORMAL}"
        ((OK++))
    else
        echo -e "${RED}DIFF${NORMAL}"
        ((DIFF++))
    fi
done

end=$(($(date +%s%N)/1000000))
echo ""

echo -e "${YELLOW}`expr $end - $begin` ms${NORMAL} ${GREEN}${OK} OK${NORMAL} ${RED}${DIFF} DIFF${NORMAL}"
if [[ ${DIFF} -eq 0 ]]; then
    exit 0
else
    exit 2
fi

